---
# tasks file for mablanco.antirootkits

- name: antirootkits_mail_from should be defined
  assert:
    that:
    - antirootkits_mail_from is defined and antirootkits_mail_from != ''
    msg: "Set the value of 'antirootkits_mail_from' in either the inventory file or the playbook invoking this role."

- name: antirootkits_mail_to should be defined
  assert:
    that:
    - antirootkits_mail_to is defined and lynis_report_to != ''
    msg: "Set the value of 'antirootkits_mail_to' in either the inventory file or the playbook invoking this role."

- name: install tools
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
  - rkhunter
  - chkrootkit
  - unhide

- name: rkhunter | enable cron scheduled runs
  lineinfile:
    dest: "/etc/default/rkhunter"
    regexp: "^CRON_DAILY_RUN="
    line: "CRON_DAILY_RUN=\"true\""
    state: present

- name: rkhunter | enable weekly database updates
  lineinfile:
    dest: "/etc/default/rkhunter"
    regexp: "^CRON_DB_UPDATE="
    line: "CRON_DB_UPDATE=\"true\""
    state: present

- name: rkhunter | setup receiver email address for reports
  lineinfile:
    dest: "/etc/default/rkhunter"
    regexp: "^REPORT_EMAIL="
    line: "REPORT_EMAIL=\"{{ antirootkits_mail_rcpt }}\""
    state: present

- name: rkhunter | enable receiver email address for warnings
  lineinfile:
    dest: "/etc/rkhunter.conf"
    regexp: "^#MAIL-ON-WARNING="
    line: "MAIL-ON-WARNING=\"{{ antirootkits_mail_rcpt }}\""
    backrefs: yes
    state: present

- name: rkhunter | remove void receiver email address for warnings (if present)
  lineinfile:
    dest: "/etc/rkhunter.conf"
    regexp: "^MAIL-ON-WARNING=\"\"$"
    state: absent

- name: rkhunter | setup receiver email address for warnings
  lineinfile:
    dest: "/etc/rkhunter.conf"
    regexp: "^MAIL-ON-WARNING="
    line: "MAIL-ON-WARNING=\"{{ antirootkits_mail_rcpt }}\""
    state: present

- name: rkhunter | whitelist /dev/shm/network/ifstate
  lineinfile:
    dest: "/etc/rkhunter.conf"
    insertafter: "^#ALLOWDEVFILE="
    line: "ALLOWDEVFILE=\"/dev/shm/network/ifstate\""
    state: present

- name: chkrootkit | enable daily scheduled runs
  lineinfile:
    dest: "/etc/chkrootkit.conf"
    regexp: "^RUN_DAILY="
    line: "RUN_DAILY=\"true\""
    state: present
